/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-06-02 15:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"img/title.ico\">\r\n");
      out.write("\t\r\n");
      out.write("    <!-- Bootstrap -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap_3.0.3/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/main_css/supersized.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/main_css/main.css\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->\r\n");
      out.write("    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->\r\n");
      out.write("    <!--[if lt IE 9]>\r\n");
      out.write("        <script src=\"http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.min.js\"></script>\r\n");
      out.write("        <script src=\"http://cdn.bootcss.com/respond.js/1.3.0/respond.min.js\"></script>\r\n");
      out.write("    <![endif]-->\r\n");
      out.write("<title>用户登录</title>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar canRegister=true;\r\n");
      out.write("\tfunction CheckNull(){\r\n");
      out.write("\t\tif(document.getElementById(\"userName\").value==\"\"||document.getElementById(\"password\").value==\"\"){\r\n");
      out.write("\t\t\talert(\"用户名或者密码不能为空！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkRNull(){\r\n");
      out.write("\t\tvar a=document.getElementById(\"NewUsername\").value;\r\n");
      out.write("\t\tvar b=document.getElementById(\"NewNickname\").value;\r\n");
      out.write("\t\tvar c=document.getElementById(\"NewPassword\").value;\r\n");
      out.write("\t\tvar d=document.getElementById(\"RNewPassword\").value;\r\n");
      out.write("\t\t//var e=document.getElementById(\"NewEmail\").value;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(a==\"\"||b==\"\"||c==\"\"||d==\"\"){\r\n");
      out.write("\t\t\talert(\"信息不完整，* 为必填项！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if(canRegister==false){\r\n");
      out.write("\t\t\talert(\"该用户名已存在！\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}else if(document.getElementById(\"IdRNewPassword\")!=document.getElementById(\"IdNewPassword\")){\r\n");
      out.write("\t\t\talert(\"密码不一致，请核对\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"RNewPassword\").value=\"\";\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction RequestForRegister(){\r\n");
      out.write("\t\t//nameValid\r\n");
      out.write("\t\tif(document.getElementById(\"NewUsername\").value!=\"\"){\r\n");
      out.write("\t\t\tvar userRequest=null;\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\tuserRequest=new XMLHttpRequest();\r\n");
      out.write("\t\t\t}else if(window.ActiveXObject){\r\n");
      out.write("\t\t\t\tuserRequest=new ActiveXObject(\"Microsoft.XMLHttp\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(userRequest){\r\n");
      out.write("\t\t\t\tuserRequest.open(\"get\",\"VerifyRegister?newUsername=\"+document.getElementById(\"NewUsername\").value,true);\r\n");
      out.write("\t\t\t\tuserRequest.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\tif(userRequest.readyState==4&&userRequest.status==200){\r\n");
      out.write("\t\t\t\t\t\t//判断ajax返回结果\r\n");
      out.write("\t\t\t\t\t\tif(userRequest.responseText==\"YES\"){\r\n");
      out.write("\t\t\t\t\t\t\tcanRegister=true;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"nameValid\").innerHTML=\"用户名可用\";\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\tcanRegister=false;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"nameValid\").innerHTML=\"用户名已存在\";\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tuserRequest.send();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GetNewUsernameFocus(){\r\n");
      out.write("\t\tdocument.getElementById(\"nameValid\").innerHTML=\"\";\r\n");
      out.write("\t\tdocument.getElementById(\"NewUsername\").value=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction RequestForLogin(){\r\n");
      out.write("\t\t\tvar loginRequest=null;\r\n");
      out.write("\t\t\tif(window.XMLHttpRequest){\r\n");
      out.write("\t\t\t\tloginRequest=new XMLHttpRequest();\r\n");
      out.write("\t\t\t}else if(window.ActiveXObject){\r\n");
      out.write("\t\t\t\tloginRequest=new ActiveXObject(\"Microsoft.XMLHttp\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(loginRequest){\r\n");
      out.write("\t\t\t\tloginRequest.open(\"get\",\"VerifyLogin?username=\"+document.getElementById(\"userName\").value+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"&password=\"+document.getElementById(\"password\").value,true);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tloginRequest.onreadystatechange=function(){\r\n");
      out.write("\t\t\t\t\tif(loginRequest.readyState==4&&loginRequest.status==200){\r\n");
      out.write("\t\t\t\t\t\t//判断ajax返回结果\r\n");
      out.write("\t\t\t\t\t\tif(loginRequest.responseText==\"YES\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"usernameValid\").innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"passwordValid\").innerHTML=\"\";\r\n");
      out.write("\t\t\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t\t}else if(loginRequest.responseText==\"WRONG_USERNAME\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"usernameValid\").innerHTML=\"用户名不存在\";\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}else if(loginRequest.responseText==\"WRONG_PASSWORD\"){\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"passwordValid\").innerHTML=\"密码错误\";\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tloginRequest.send();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GetUsernameFocus(){\r\n");
      out.write("\t\tdocument.getElementById(\"usernameValid\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction GetPasswordFocus(){\r\n");
      out.write("\t\tdocument.getElementById(\"passwordValid\").innerHTML=\"\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\" >\r\n");
      out.write("        <h1>合同管理系统</h1>\r\n");
      out.write("        <form class=\"form-horizontal\" role=\"form\" action=\"Login\" method=\"post\" onsubmit=\"return CheckNull()\">\r\n");
      out.write("          \r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <div class=\"col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4\">\r\n");
      out.write("              <input name=\"userName\" onfocus=\"GetUsernameFocus()\" type=\"text\" class=\"form-control form-control-white\" style=\"background:rgba(100,100,100,.15);border:1px solid #ffffff\" id=\"userName\" placeholder=\"用户名:\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <label id=\"usernameValid\" style=\"color:red;\"></label>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <div class=\"col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4\">\r\n");
      out.write("              <input name=\"password\" onblur=\"RequestForLogin()\" onfocus=\"GetPasswordFocus()\" type=\"password\" class=\"form-control form-control-white\" style=\"background:rgba(100,100,100,.15);border:1px solid #ffffff\" id=\"password\" placeholder=\"密   码:\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <label id=\"passwordValid\" style=\"color:red;\"></label>\r\n");
      out.write("          </div>\r\n");
      out.write("          ");

	          	Integer result=(Integer)request.getAttribute("result");
		        if(result!=null){
		        	out.println("<div class=\"form-group \">");
		        	out.println("<div class=\"col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4\">");
		        	out.println("<div class=\"alert alert-warning alert-dismissable\" style=\"background-color:rgba(255,255,255,0.1); border:0px\">");
		        	out.println("<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>");
		        	if(result==StatusCode.ERROR_NOUSERNAME){
		    			out.println("<strong>错误：&nbsp;&nbsp;</strong>用户名不存在!");
		    		}else if(result==StatusCode.ERROR_WRONGPASSWORD){
		    			out.println("<strong>错误：&nbsp;&nbsp;</strong>密码错误!");
		    		}else if(result==StatusCode.ERROR_NORIGHT){
		    			out.println("<strong>提示：&nbsp;&nbsp;</strong>你还没有权限，等管理员给你分配权限吧!");
		    		}else if(result==StatusCode.PROMPT_LOGIN_OUT){
		    			out.println("<strong>提示：&nbsp;&nbsp;</strong>注销成功!");
		    		}else if(result==StatusCode.ERROR_LOGIN_OUT){
		    			out.println("<strong>警告：&nbsp;&nbsp;</strong>您已经注销登录或者登陆超时，请重新登录!");
		    		}else if(result==StatusCode.PROMPT_REGISTER_SUCCESS){
		    			out.println("<strong>提示：&nbsp;&nbsp;</strong>您已经注册成功，但是还不能登录哦，静待管理员分配权限吧!");
		    		}else if(result==StatusCode.ERROR_LOGIN_OUT){
		    			out.println("<strong>错误：&nbsp;&nbsp;</strong>抱歉，注册失败!");
		    		}
		        	//out.println(result);
		    		out.println("</div></div></div>");
		        }
			  
	      
      out.write("\r\n");
      out.write("          <div class=\"form-group\">\r\n");
      out.write("            <div class=\"col-xs-offset-2 col-xs-8 col-sm-offset-4 col-sm-4\" align=\"center\">\r\n");
      out.write("              <button type=\"submit\" class=\"btn btn-info btn-block\" id=\"登录\">登录</button>\r\n");
      out.write("              <button class=\"btn btn btn-info btn-block\" data-toggle=\"modal\" data-target=\"#myModal\">注册</button>                \r\n");
      out.write("                   \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </form>\r\n");
      out.write("        \r\n");
      out.write("      <!-- Modal -->\r\n");
      out.write("      <div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">                \r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">&times;</button>\r\n");
      out.write("                <h4 class=\"modal-title\" id=\"myModalLabel\">注册成为新用户</h4>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <form class=\"form-horizontal\" role=\"form\" action=\"Register\" method=\"post\">\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  for=\"用户名\" class=\"col-sm-3 control-label\">用户名：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input  name=\"NewUsername\"  type=\"text\" class=\"form-control\" id=\"NewUsername\" onblur=\"RequestForRegister()\" onfocus=\"GetNewUsernameFocus()\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label for=\"用户名\" class=\"col-sm-3 control-label\" style=\"color:#FF0000;text-align:left;\">* &nbsp;&nbsp;<label id=\"nameValid\"></label></label>\r\n");
      out.write("                        <!-- <label for=\"用户名\" class=\"col-sm-2 control-label\" style=\"color:#FF0000;text-align:left;\">已存在</label> -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"昵称\" class=\"col-sm-3 control-label\">昵称：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input name=\"NewNickname\" type=\"text\" class=\"form-control\" id=\"NewNickname\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label for=\"昵称\" class=\"col-sm-3 control-label\" style=\"color:#FF0000;text-align:left;\">*</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"密码\" class=\"col-sm-3 control-label\">密码：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input name=\"NewPassword\" type=\"password\" class=\"form-control\" id=\"NewPassword\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label for=\"密码\" class=\"col-sm-3 control-label\" style=\"color:#FF0000;text-align:left;\">*</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label  for=\"重复密码\" class=\"col-sm-3 control-label\">重复密码：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input name=\"RNewPassword\" type=\"password\" class=\"form-control\" id=\"RNewPassword\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <label for=\"重复密码\" class=\"col-sm-3 control-label\" style=\"color:#FF0000;text-align:left;\">*</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"邮件\" class=\"col-sm-3 control-label\">邮件：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input name=\"NewEmail\" type=\"text\" class=\"form-control\" id=\"NewEmail\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label for=\"电话\" class=\"col-sm-3 control-label\">电话：</label>\r\n");
      out.write("                        <div class=\"col-xs-3 col-sm-6\">\r\n");
      out.write("                          <input name=\"NewTel\" type=\"text\" class=\"form-control\" id=\"NewTel\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"form-group\">\r\n");
      out.write("                        <label class=\"col-sm-3 col-sm-offset-3 control-label\" style=\"color:#FF0000;text-align:left;\">*为必填选项</label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">关闭</button>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-info\" onclick=\"return checkRNull()\">注册</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                   </form>\r\n");
      out.write("                  </div><!-- /.modal-content -->\r\n");
      out.write("                </div><!-- /.modal-dialog -->\r\n");
      out.write("              </div>\r\n");
      out.write("         </div><!-- /.modal -->\r\n");
      out.write("         ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Footer.jsp", out, false);
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\r\n");
      out.write("    <script src=\"css/bootstrap_3.0.3/js/jquery-2.0.2.js\"></script>\r\n");
      out.write("    <!-- Include all compiled plugins (below), or include individual files as needed -->\r\n");
      out.write("    <script src=\"css/bootstrap_3.0.3/js/bootstrap.js\"></script>\r\n");
      out.write("    <script src=\"css/main_js/supersized.3.2.7.min.js\"></script>\r\n");
      out.write("    <script src=\"css/main_js/supersized-init.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
